# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d55fa64f84358322b25f1efd357d023f78ccdb2b2df20d0addc9ee85ae2417d4d091371c418ebe51938660217d17f54514a33b767715993a78956920558bd88

test:
  secret_key_base: 5aa2a4417ae571a9d28b26b1c4878774c4d2412b88eb5fbdab48f5d896a29b390df241e31e0237bb5e7662439f385a0d1c5c9873d82dd6db5b8220d53229f158

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
